name: CS website 

on:
  pull-requests:
    branches: [ main  ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2

      - name: Setup .Net 6.0
        - uses: actions/setup-dotnet@v3
          with:
            dotnet-version: '6.0.x'
      
      - name: Restore dependencies
        - run: dotnet restore

      - name: Build app
        - run: dotnet build --configuration Release --no-restore
